---

- name: Looping with Dictionaries
  hosts: local
  vars:
    my_devices:
      device1:
        ip_addr: 10.10.10.1
        device_type: cisco_ios
       
      device2:
        ip_addr: 10.10.20.1
        device_type: cisco_ios
         
      device3:
        ip_addr: 10.10.30.1
        device_type: juniper_junos
     
  tasks:
    -  name: Key <> Value pairs
       debug:
         msg: "{{ item }}"
       with_dict: "{{ my_devices }}"
       
    -  name: Just KEY
       debug:
         msg: "{{ item.key }}"
       with_dict: "{{ my_devices }}"
       
    -  name: Just VALUE
       debug:
         msg: "{{ item.value }}"
       with_dict: "{{ my_devices }}"
       
    -  name: Just SUB-VALUE "IP_ADDR"
       debug:
         msg: "{{ item.value.ip_addr }}"
       with_dict: "{{ my_devices }}"